### ISSUE TITLE
Create logos for individual games

### ISSUE THREAD

**Issue by k1dubv1** [se310-Team4/KKDZ#101]
Individual logos to be used as visuals for the buttons in the home page.

**Comment by Destiny-02** [comment]
Please include why this feature is needed (even though it might be obvious we still need to follow the [contributing guidelines](https://github.com/se310-Team4/KKDZ/blob/main/CONTRIBUTING.md)).

**Comment by k1dubv1** [comment]
Just for visual appearance. The home page will look more interesting and visually appealing than if it were just to have buttons containing just the names for each game ("capidle", "liedle", "2048 expert"). Not a necessary feature but thought it would be good to include.

**Comment by Destiny-02** [comment]
Approved.  Note that 2 _other_ members must give approval before removing the `pending` tag.

**Comment by k-yle** [comment]
approved

**Comment by k1dubv1** [comment]
Created the following logo designs:

![capidle-logo](https://user-images.githubusercontent.com/79814736/185886797-bec4ee1f-a7f7-4c42-b7ce-939f8f6476be.png)

![liedle-logo](https://user-images.githubusercontent.com/79814736/185886803-da10a081-104f-419b-8890-d433e8bace19.png)

![a2048expert-logo](https://user-images.githubusercontent.com/79814736/185886805-6780cf97-80b6-4960-8f62-664a9fad581b.png)

**Comment by k1dubv1** [comment]
will center the question mark in the liedle logo better^
