### ISSUE TITLE
Create details and game images for the homepage

### ISSUE THREAD

**Issue by k1dubv1** [se310-Team4/KKDZ#102]
Add a short summary and an example image about each individual game to the home page when button is hovered. Functionality is already implemented.

**Comment by Destiny-02** [comment]
Please include why this feature is needed (even though it might be obvious we still need to follow the [contributing guidelines](https://github.com/se310-Team4/KKDZ/blob/main/CONTRIBUTING.md)).

**Comment by k1dubv1** [comment]
Gives the user a bit more information about the game itself. A short description to pique the user's interest and let them understand what kind of game it is. More like a summary rather than how the play the game so it will not collide with/steal the help modal's functionality.

**Comment by Destiny-02** [comment]
Approved (need one more approval before issue is taken off `pending`)

**Comment by k-yle** [comment]
approved
