### ISSUE TITLE
Fix typos and ensure consistency

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#103]
There are many minor problems in the code that were not picked up in past code reviews. 

**Includes**
- Spelling / typos
- Checking that all comments are appropriate/useful
- Naming conventions
- Spacing
- Line breaks
- Indentation
- Other standards

**Why this is required**
- Improve understandability and maintainability
- Set standards/expectations for future contributors

**Comment by k1dubv1** [comment]
approved

**Comment by k-yle** [comment]
approved. if you want, we could install [prettier](https://prettier.io) and/or [eslint](https://eslint.org) to automatically fix some of these issues

**Comment by Kanelmis** [comment]
Approved

**Comment by Destiny-02** [comment]
Reopening this issue as Quality Gate is failing due to code duplication
