### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#108]
Add a favicon to the website and make sure that it shows on both the main page and the mini-game pages. 
There is currently no favicon on any of the pages. Adding a favicon will help make the website look more appealing/professional. 
![image](https://user-images.githubusercontent.com/78716153/186011684-01ac54f6-3de8-4ed0-824a-7b53bfd78045.png)

**Comment by k-yle** [comment]
approved

**Comment by k1dubv1** [comment]
approved
