### ISSUE TITLE
The home page is not responsive

### ISSUE THREAD

**Issue by atan958** [se310-Team4/KKDZ#114]
Users with narrower screens won't be able to read the descriptions properly as the buttons block them. Additionally, the images shrink down quite rapidly with respect to the browser window. This significantly reduces the site's usability as the user can't view the content very well, which does not make for a good user experience.

![image](https://user-images.githubusercontent.com/79767691/192719557-ca4aecf1-c4d6-4e6f-87fb-fae59be37616.png)

**Comment by lche262** [comment]
Looks good to me! It is good to make the description text and button resize responsively.

**Comment by JosiahBull** [comment]
This is a great thing to work on! Could be good to investigate wider aspect screen ratios too, not just mobile displays.
