### ISSUE TITLE
Liedie shows incorrect colour to some of the attempts

### ISSUE THREAD

**Issue by lche262** [se310-Team4/KKDZ#120]
**Description**
Liedie shows incorrect colour in some of the attempts. However, it could pass the tests. It might only happen in replicated words or it is only noticeable while we are using the same word but the colours are different.

**Steps to reproduce**
1. Open Liedie
2. Enter replicated words
3. The colour of the letter varies.

![image](https://user-images.githubusercontent.com/79813230/192806350-f43cfd30-cb58-4a3f-b5eb-bd16ebf4bbb1.png)

**Expected behaviour**
Liedie shows the colour correctly. Or we can limit users to input the same word to prevent the bug happens.

**Actual behaviour**
Liedie shows incorrect colour when using the same word, or noticeable colour assigned for each attempt for a spectacular reason.

**Potential cause**
Replicated word input.

**Comment by hmin697** [comment]
As its written in liedle/index.html there is 8% chance that a letter can Iie. This is supposed to happen

**Comment by lche262** [comment]
Sorry for misunderstood the game. I will close this issue now.
