### ISSUE TITLE
2048 Expert game does not fit the page when the browser window is made narrower

### ISSUE THREAD

**Issue by atan958** [se310-Team4/KKDZ#123]
When narrowing down the browser window, the board sticks out of the page, past the length of the nav bar. This is not aesthetically pleasing, and forces the user to have to scroll horizontally in order to see all parts of the board.

![image](https://user-images.githubusercontent.com/79767691/192899906-60b16fa5-4ccf-437b-b169-f8f03ce277ca.png)

**Comment by Zasheus** [comment]
Approved
