### ISSUE TITLE
Zoom out function is not working in Capidle Map

### ISSUE THREAD

**Issue by lche262** [se310-Team4/KKDZ#128]
**Description**
The zoom-out button in Map in Capidle is not working. It can be zoomed out with other methods.

**Steps to reproduce**
1. Open Capidle
2. Click on Zoom out ( Minus button) 
3. No response

**Expected behaviour**
The map zooms out once we press the button.

**Potential cause**
I don't have any idea, it might be has something to do with the map function inside Capitle\script\render.js But it is out of my ability and I am not very certain about it.

**Comment by hmin697** [comment]
Approved! This might be critical for mobile users

**Comment by JosiahBull** [comment]
This is very important to fix quickly as it's a significant usability hurdle.
