### ISSUE TITLE
Page element moves while pressing up/down arrow key in the small window

### ISSUE THREAD

**Issue by lche262** [se310-Team4/KKDZ#129]
**Description**
While Opening 2048expert with a smaller window, the page keeps scrolling up and down while playing since the element could not be fully shown in the window. 

**Solution**
We can make the size of the elements responsive/ enable the scrolling function on the page to prevent this happen.
![2022-09-29_18-34-04_AdobeExpress](https://user-images.githubusercontent.com/79813230/192948500-ec4aa008-1e7f-44f8-934b-c9e8032e9d66.gif)

**Comment by hmin697** [comment]
Approved!

**Comment by JosiahBull** [comment]
Looks good!
