### ISSUE TITLE
User can interact with 2048 and Capidle while window is open

### ISSUE THREAD

**Issue by JosiahBull** [se310-Team4/KKDZ#133]
When the help modal is present, you can still use arrow keys to control the game. The functionality implemented for Liedle in #81 should be replicated for 2048 and Capidle, by listening for events emitted by the help modal.

**Steps to reproduce**
- Run `npm start`.
- Visit `http://localhost:1234/capidle/index.html`.
- There should be a dialogue already open. This dialogue can also be brought back with the ❔ symbol in the navigation bar. 
- Press the arrow keys
- You will see the blocks moving around in the background

**Potential cause of the bug**
No extra logic to disable the underlying contents has been implemented.

**Comment by lche262** [comment]
Approve! good thinking!
