### ISSUE TITLE
Add a Memory Game

### ISSUE THREAD

**Issue by JosiahBull** [se310-Team4/KKDZ#136]
**Description**
We have games for language and thinking ahead, I think it would be great to have a game that improves memory retention. I'd like to see a game that flashes colors in a certain order/with sounds and then users have to call the colors/sounds in the same order.

The patterns could become increasingly complex as time goes on, until a user fails. Could do lives, or instant fails - not sure at this point.

Is this something we could add?

**Comment by Zasheus** [comment]
Approved

**Comment by lche262** [comment]
Approved!
