### ISSUE TITLE
The best scores modal doesn't include the Tactong game.

### ISSUE THREAD

**Issue by atan958** [se310-Team4/KKDZ#138]
Currently, the best scores modal isn't keeping track of the newly added memory game Tactong. This is the only game whose best score isn't being kept track of, hence, is causing inconsistency in the web app.

![image](https://user-images.githubusercontent.com/79767691/193954007-f72908ce-048d-49f3-82bd-3e51e030958f.png)

**Comment by JosiahBull** [comment]
Good catch, will fix this asap!

**Comment by Zasheus** [comment]
Approved!
