### ISSUE TITLE
The image for the Tactong's game description on the home page hangs too far down.

### ISSUE THREAD

**Issue by atan958** [se310-Team4/KKDZ#139]
Currently, on the home page, when displaying Tactong's game description, its associated image is partly obstructed by the buttons. This prevents users from seeing the entire image at once, which is inconsistent with other game descriptions, hence, makes for bad user experience.

![image](https://user-images.githubusercontent.com/79767691/193955356-f5fd6016-dbb4-460a-9bac-e1941468f6c2.png)

**Comment by JosiahBull** [comment]
Yep, absolutely needs to be fixed!

**Comment by Zasheus** [comment]
Approved!
