### ISSUE TITLE
The scoring for Tactong starts prematurely

### ISSUE THREAD

**Issue by atan958** [se310-Team4/KKDZ#140]
**Description**
When starting a new game for Tactong, the score increments from 0 to 1 before the user even clicks any of the buttons.

**Steps to reproduce**
1. Open Tactong
2. Click anywhere on the Tactong screen

**Expected behaviour**
The score should remain at 0 until after the user has pressed the correct button(s) of the given round.

**Actual behaviour**
The score increments directly after the user clicks on the screen to start a new game.

**Potential cause**
The `startNextGame()` function increments the `gameCount` variable (i.e. the tracker for the current score) at the start of each round.

**Comment by JosiahBull** [comment]
Good catch! This was actually intentional as I wanted the user to always have `1` score even if they fail right away. I can totally see how that is confusing though, so I support changing it. :)
