### ISSUE TITLE
Add a Pokemon-inspired Game

### ISSUE THREAD

**Issue by atan958** [se310-Team4/KKDZ#147]
Seeing as a lot of our users (engineering students) are long-time fans of the Pokemon franchise, adding a new game inspired by it will surely pique their interest.

The "Who's that pokemon?" mini-game is already very well-known among fans, hence, I would suggest we implement a game that is based on that. 

But sticking to the BrainGain theme, we will definitely have to add our own it, etc. to make it unique.

**Comment by JosiahBull** [comment]
Oh that's a great idea! Sounds fun :D
