### ISSUE TITLE
Pokettiles not playable

### ISSUE THREAD

**Issue by JosiahBull** [se310-Team4/KKDZ#157]
While trying to test pocket tiles, I was unable to start the game:
Steps to reproduce:
1. go to production version of app
2. navigate to pocket tiles
3. close the modal
4. the game doesn't start

![image](https://user-images.githubusercontent.com/29187591/196385971-51e5b175-6781-41e7-a371-9e2ec18896ee.png)

**Comment by hmin697** [comment]
approved.
