### ISSUE TITLE
Create app CSS

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#23]
Create the CSS that will be used across all the mini-games and homepage. Include headings, font, text colour, background colour, button styling, dialogue styling etc.

**Comment by k1dubv1** [comment]
[https://fonts.google.com/specimen/Figtree?preview.text=QWERTYUIOPASDFGHJKLZXCVBNM&preview.text_type=custom](url)
[https://fonts.google.com/specimen/Open+Sans?category=Sans+Serif,Handwriting,Monospace&preview.text=QWERTYUIOPASDFGHJKLZXCVBNM&preview.text_type=custom](url)
[https://fonts.google.com/specimen/Montserrat?category=Sans+Serif,Handwriting,Monospace&preview.text=QWERTYUIOPASDFGHJKLZXCVBNM&preview.text_type=custom](url)
[https://fonts.google.com/specimen/Varela+Round?category=Serif,Sans+Serif&preview.size=34&preview.text=QWERTYUIOPASDFGHJKLZXCVBNM&preview.text_type=custom](url)

4 possible fonts above
