### ISSUE TITLE
SonarCloud analyses code coverage on test files

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#53]
SonarCloud analyses code coverages on all JavaScript files, including Cypress tests. This brings the code coverage down, causing the Quality Gate to fail. 

Potential fix: 
Add `sonar.coverage.exclusions=./cypress` to `sonar-project.properties`

![image](https://user-images.githubusercontent.com/78716153/183367113-b0662bba-8138-4c83-9e00-1fee789ddd3c.png)

**Comment by k-yle** [comment]
this is weird, `sonar.coverage.exclusions=./cypress` sounds like a good idea...

**Comment by k1dubv1** [comment]
approved

**Comment by Kanelmis** [comment]
👍
