### ISSUE TITLE
Decide on application name

### ISSUE THREAD

**Issue by k1dubv1** [se310-Team4/KKDZ#54]
Come up with a name for the application title, discuss with all collaborators. Reflect name change in repository description, README and code (where applicable).

**Comment by Destiny-02** [comment]
approved

**Comment by k-yle** [comment]
approved

**Comment by k-yle** [comment]
one suggestion from yesterday's meeting was `CoolBrainGames` (like CoolMathGames)

**Comment by Kanelmis** [comment]
Approved

**Comment by k1dubv1** [comment]
Possible names:

Simple, makes sense:
- BrainGain (gaining brain power)
- The BrainBench (alternatively The BrainMark) -> brain + benchmark
- coolbraingames 
- logicool

Makes sense but not easy to understand/possibly bad connotations:
- BrainPain
- geniYES
- Brain INSANE

really simple:
- Train your Brain (or Tame your Brain)
- mastermind
- THINK! (or JUST THINK!)

really stupid:
- litty witty
- Kool Kids Dont Zzz (KKDZ)

just sounds good:
- wisdomination
- do you mind?

**Comment by k1dubv1** [comment]
All members agreed on "BrainGain"

**Comment by Destiny-02** [comment]
Are you able to update the repository description, README and code (where there is a mention of KKDZ / KKDZ games)? We will leave the repository name as KKDZ since it was linked in the project proposal.
