### ISSUE TITLE
Badge in README not showing

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#55]
Build & Test badge doesn't show as expected.

**Potential cause**
URL is broken

**Potential Fix:**
Change URL to https://github.com/se310-Team4/KKDZ/actions/workflows/build_test.yml/badge.svg

**Screenshot**

![image](https://user-images.githubusercontent.com/78716153/183388356-0e988077-0d95-430e-ac34-1420622fd425.png)

**Comment by k-yle** [comment]
approved

sorry this was my mistake, [the URL in the comment above](https://github.com/se310-Team4/KKDZ/issues/55#issue-1331616478) is the correct one

**Comment by Kanelmis** [comment]
approved

**Comment by k-yle** [comment]
reopening, #67 introduced a regression
