### ISSUE TITLE
Use a consistent navbar design across all pages

### ISSUE THREAD

**Issue by k-yle** [se310-Team4/KKDZ#66]
Follow up from https://github.com/se310-Team4/KKDZ/pull/65#discussion_r940965241

Our design would be more cohesive and understandable if every page used the same navbar, with the same design.

The current navbar from Capidle would be a good place to start.

**Comment by Destiny-02** [comment]
approved

**Comment by Kanelmis** [comment]
Approved

**Comment by Destiny-02** [comment]
Reopening this issue as 2048 Expert is yet to implement the navbar
