### ISSUE TITLE
Sonarcloud config still has issues

### ISSUE THREAD

**Issue by k-yle** [se310-Team4/KKDZ#68]
The Sonarcloud config still has issues:
 - for some bizarre reason the CI runs tests on `main` instead of the PR. e.g. tests should have failed on #62
 - the sonarcloud UI doesn't distinguish branches properly.

**Comment by Destiny-02** [comment]
approved

**Comment by Kanelmis** [comment]
Approved

**Comment by k1dubv1** [comment]
Approved

**Comment by k-yle** [comment]
re-opening, #67 did not fully fix this
