### ISSUE TITLE
User can interact with the underlying window when the modal window is open

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#81]
When the help dialogue is open, you can type or tab through components on the screen. In Liedle, you can type a word and play the game without closing the dialogue. This is a problem because users will want to read and understand the game before using up their guesses. 

**Steps to reproduce**
- Run `npm start`.
- Visit `http://localhost:1234/liedle/index.html`.
- There should be a dialogue already open. This dialogue can also be brought back with the ❔ symbol in the navigation bar. 
- Type some letters
- Close the window using the x button or by clicking outside of the dialogue
- You will see the letters you just typed

**Potential cause of the bug**
No extra logic to disable the underlying contents has been implemented.

**Comment by Kanelmis** [comment]
👍

**Comment by k-yle** [comment]
approved. this issue doesn't seem to affect the other mini games. Maybe [this check](https://github.com/se310-Team4/KKDZ/blob/03e0038/src/liedle/index.js#L88) needs to also check whether the modal is open
