### ISSUE TITLE
Liedle incorrectly colours tiles for words with repeated letters

### ISSUE THREAD

**Issue by Destiny-02** [se310-Team4/KKDZ#90]
**Description**
Liedle incorrectly colours tiles for words with repeated letters. More specifically, only the first occurrence of the repeated letters is coloured correctly, the rest are coloured yellow. This happens when the word guessed is incorrect or correct so is not a product of the 8% lie rate (correct guesses should always be fully coloured green). 

**Steps to reproduce**
This bug happens with certain words so we will need to modify the code 
- Find `liedle/index.js`
- Replace the line `import { dictionary } from './dictionary.js'` with `const dictionary = ['happy']` 
- Visit `http://localhost:1234/liedle/index.html` and close the help dialogue
- Type `happy`

**Expected behaviour**
All letters should be green because the whole word is correct. The game should also end. 

**Actual behaviour**
The 4th letter (2nd P) is yellow. The game does end as expected. 
![image](https://user-images.githubusercontent.com/78716153/184870708-755eadf7-2ef1-4baa-ae55-a16e91c26edd.png)

**Potential cause**
The function `colourLetter(tile)` looks for the index of the first occurence of the letter which might be different to its actual position. 

**Potential fix**
Use `secretWord.charAt(tile.dataset.colIndex) === tile.innerHTML` to check if the letter is the right letter and is in the right position.

**Comment by Kanelmis** [comment]
Approved

**Comment by k-yle** [comment]
approved
