### ISSUE TITLE
hide help modal once the user has seen it

### ISSUE THREAD

**Issue by k-yle** [se310-Team4/KKDZ#98]
It may become frustrating if the help modal pops up every time a user opens the page. 

This is only an issue for people who repeatedly visit the website. The user could still click the <kbd>❔</kbd> icon to show the help modal.

One possible solution: 

[when the modal is closed:](https://github.com/se310-Team4/KKDZ/blob/cb72bd5/src/modal.js#L29-L32)

```diff
+ localStorage["seen-modal-" + location] = true;
```

[And before opening the modal:](https://github.com/se310-Team4/KKDZ/blob/cb72bd5/src/modal.js#L47-L48)
```diff
// open the window by default
- openModal();
+ if (!localStorage["seen-modal-" + location]) openModal();
```

**Comment by Destiny-02** [comment]
approved

**Comment by k1dubv1** [comment]
approved

**Comment by lche262** [comment]
The possible solution did not work, even if openModel() is not called, the help model still appears.
