### ISSUE TITLE
2048 Expert game ends prematurely when board is full but still contains possible merges

### ISSUE THREAD

**Issue by k1dubv1** [se310-Team4/KKDZ#99]
**Description**
The game finishes prematurely when the board is filled up rather than when there are no more possible merges. The final message appears and the game is restarted.

**Steps to reproduce**

1. Find `2048-expert/index.js`
2. Add the following to the end of the file
```
for (let i = 0; i < 36; i=i+4) {
    cells[i].innerHTML = 2;
    cells[i+1].innerHTML = 4;
    cells[i+2].innerHTML = 4;
    cells[i+3].innerHTML = 2;
  }
addColours()
```
3. Run `npm start`
4. Visit `http://localhost:1234/2048-expert/index.html`
(Page should look like this)
![image](https://user-images.githubusercontent.com/79814736/185742912-d2630a38-524e-46f9-b981-ca2e37e927a6.png)

5. Press the down or up button

**Expected behaviour**
Game should still continue, the left and right buttons can be pressed to merge remaining tiles

**Actual behaviour**
Game ends and losing message shows up

**Potential cause**
`checkLost()` checks for empty cells rather than if any cells can still be merged

**Comment by Destiny-02** [comment]
approved

**Comment by Kanelmis** [comment]
Approved
